name: java-api-build
on:
  push:
    paths:
      - ".github/workflows/java-api-build.yml"
      - "api/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
      - name: 'Java version build info'
        run: echo java -version

      - name: List .class files
        run: ls src/**/*.class || echo "No .class files found"